// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuscarUsuarios(arg1) {
  return window['go']['main']['App']['BuscarUsuarios'](arg1);
}

export function CrearFuncion(arg1, arg2) {
  return window['go']['main']['App']['CrearFuncion'](arg1, arg2);
}

export function CrearModulo(arg1) {
  return window['go']['main']['App']['CrearModulo'](arg1);
}

export function CrearUsuario(arg1) {
  return window['go']['main']['App']['CrearUsuario'](arg1);
}

export function DarDeAltaUsuario(arg1) {
  return window['go']['main']['App']['DarDeAltaUsuario'](arg1);
}

export function DarDeBajaUsuario(arg1, arg2) {
  return window['go']['main']['App']['DarDeBajaUsuario'](arg1, arg2);
}

export function EliminarFuncion(arg1) {
  return window['go']['main']['App']['EliminarFuncion'](arg1);
}

export function EliminarModulo(arg1) {
  return window['go']['main']['App']['EliminarModulo'](arg1);
}

export function GenerarPassword() {
  return window['go']['main']['App']['GenerarPassword']();
}

export function GuardarUsuario(arg1) {
  return window['go']['main']['App']['GuardarUsuario'](arg1);
}

export function ListarEstadisticasFunciones() {
  return window['go']['main']['App']['ListarEstadisticasFunciones']();
}

export function ListarEstructuraModulos() {
  return window['go']['main']['App']['ListarEstructuraModulos']();
}

export function ListarFuncionesPorUsuario(arg1) {
  return window['go']['main']['App']['ListarFuncionesPorUsuario'](arg1);
}

export function ListarModulos() {
  return window['go']['main']['App']['ListarModulos']();
}

export function ListarPlanes() {
  return window['go']['main']['App']['ListarPlanes']();
}

export function ListarRegistrosFuncion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListarRegistrosFuncion'](arg1, arg2, arg3, arg4);
}

export function ListarUsuarios(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListarUsuarios'](arg1, arg2, arg3);
}

export function ListarUsuariosBaja() {
  return window['go']['main']['App']['ListarUsuariosBaja']();
}

export function ModificarFuncion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ModificarFuncion'](arg1, arg2, arg3);
}

export function ModificarModulo(arg1, arg2) {
  return window['go']['main']['App']['ModificarModulo'](arg1, arg2);
}
