// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function BuscarUsuarios(arg1:string):Promise<Array<models.User>>;

export function CrearFuncion(arg1:number,arg2:string):Promise<void>;

export function CrearModulo(arg1:string):Promise<void>;

export function CrearUsuario(arg1:models.NewUserInput):Promise<models.CreatedUser>;

export function DarDeAltaUsuario(arg1:number):Promise<void>;

export function DarDeBajaUsuario(arg1:number,arg2:string):Promise<void>;

export function EliminarFuncion(arg1:number):Promise<void>;

export function EliminarModulo(arg1:number):Promise<void>;

export function GenerarPassword():Promise<string>;

export function GuardarUsuario(arg1:main.GuardarUsuarioInput):Promise<void>;

export function ListarEstadisticasFunciones():Promise<Array<models.RecordStat>>;

export function ListarEstructuraModulos():Promise<Array<models.ModuloFuncion>>;

export function ListarFuncionesPorUsuario(arg1:number):Promise<Array<models.FuncionPermiso>>;

export function ListarModulos():Promise<Array<models.Modulo>>;

export function ListarPlanes():Promise<Array<models.Plan>>;

export function ListarRegistrosFuncion(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.RecordPage>;

export function ListarEstadisticasUsuarios():Promise<Array<models.UserStat>>;

export function ListarTop15FuncionesPorUsuario(arg1:number):Promise<Array<models.FunctionUsage>>;

export function ListarRegistrosPorUsuarioYFuncion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<models.RecordPage>;

export function ListarUsuarios(arg1:string,arg2:string,arg3:string):Promise<Array<models.User>>;

export function ListarUsuariosBaja():Promise<Array<models.User>>;

export function ModificarFuncion(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ModificarModulo(arg1:number,arg2:string):Promise<void>;
